// <auto-generated />
namespace AppArticle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_first_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_first_db));
        
        string IMigrationMetadata.Id
        {
            get { return "202204191228027_create_first_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
