// <auto-generated />
namespace AppArticle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_source_21_4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_source_21_4));
        
        string IMigrationMetadata.Id
        {
            get { return "202204210725518_update_source_21_4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
